# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doktor_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_DoktorEkrani(object):
    def setupUi(self, DoktorEkrani):
        DoktorEkrani.setObjectName("DoktorEkrani")
        DoktorEkrani.resize(533, 499)
        DoktorEkrani.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        DoktorEkrani.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_doktor_baslik = QtWidgets.QLabel(DoktorEkrani)
        self.label_doktor_baslik.setGeometry(QtCore.QRect(30, 10, 481, 81))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setLegacyWeight(75)
        self.label_doktor_baslik.setFont(font)
        self.label_doktor_baslik.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_doktor_baslik.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_doktor_baslik.setObjectName("label_doktor_baslik")
        self.label_2_doktorbilgi = QtWidgets.QLabel(DoktorEkrani)
        self.label_2_doktorbilgi.setGeometry(QtCore.QRect(40, 90, 461, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2_doktorbilgi.sizePolicy().hasHeightForWidth())
        self.label_2_doktorbilgi.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        font.setItalic(True)
        self.label_2_doktorbilgi.setFont(font)
        self.label_2_doktorbilgi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2_doktorbilgi.setStyleSheet("color :rgb(0, 0, 255)")
        self.label_2_doktorbilgi.setTextFormat(QtCore.Qt.AutoText)
        self.label_2_doktorbilgi.setWordWrap(False)
        self.label_2_doktorbilgi.setOpenExternalLinks(False)
        self.label_2_doktorbilgi.setObjectName("label_2_doktorbilgi")
        self.label_3 = QtWidgets.QLabel(DoktorEkrani)
        self.label_3.setGeometry(QtCore.QRect(230, 260, 111, 41))
        self.label_3.setObjectName("label_3")
        self.pushButton_doktor = QtWidgets.QPushButton(DoktorEkrani)
        self.pushButton_doktor.setGeometry(QtCore.QRect(180, 410, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setLegacyWeight(75)
        self.pushButton_doktor.setFont(font)
        self.pushButton_doktor.setObjectName("pushButton_doktor")
        self.textEdit_doktor_mesaj = QtWidgets.QTextEdit(DoktorEkrani)
        self.textEdit_doktor_mesaj.setGeometry(QtCore.QRect(130, 220, 271, 171))
        self.textEdit_doktor_mesaj.setObjectName("textEdit_doktor_mesaj")

        self.retranslateUi(DoktorEkrani)
        QtCore.QMetaObject.connectSlotsByName(DoktorEkrani)

    def retranslateUi(self, DoktorEkrani):
        _translate = QtCore.QCoreApplication.translate
        DoktorEkrani.setWindowTitle(_translate("DoktorEkrani", "Doktor Ekranı"))
        self.label_doktor_baslik.setText(_translate("DoktorEkrani", "Randevulu Hasta Mesaj Ekranı"))
        self.label_2_doktorbilgi.setText(_translate("DoktorEkrani", "Duyuru: Şuan da hastadan bir bilgi bulunmamaktadır."))
        self.label_3.setText(_translate("DoktorEkrani", "Doktor Mesaj Ekranı"))
        self.pushButton_doktor.setText(_translate("DoktorEkrani", "Hasta Ekranına Mesaj Gönder"))

