# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hasta_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_HastaEkrani(object):
    def setupUi(self, hasta_ekrani):
        hasta_ekrani.setObjectName("HastaEkrani")
        hasta_ekrani.resize(538, 500)
        self.label_hastabaslik = QtWidgets.QLabel(hasta_ekrani)
        self.label_hastabaslik.setGeometry(QtCore.QRect(40, 20, 481, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setLegacyWeight(75)
        self.label_hastabaslik.setFont(font)
        self.label_hastabaslik.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_hastabaslik.setObjectName("label_hastabaslik")
        self.label_2_hastabilgi = QtWidgets.QLabel(hasta_ekrani)
        self.label_2_hastabilgi.setGeometry(QtCore.QRect(50, 120, 481, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        font.setItalic(True)
        self.label_2_hastabilgi.setFont(font)
        self.label_2_hastabilgi.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_2_hastabilgi.setObjectName("label_2_hastabilgi")
        self.pushButton_hasta = QtWidgets.QPushButton(hasta_ekrani)
        self.pushButton_hasta.setGeometry(QtCore.QRect(190, 400, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setLegacyWeight(75)
        self.pushButton_hasta.setFont(font)
        self.pushButton_hasta.setStyleSheet("\n"
        "color: rgb(0, 0, 0);")
        self.pushButton_hasta.setObjectName("pushButton_hasta")
        self.textEdit_hasta_mesaj = QtWidgets.QTextEdit(hasta_ekrani)
        self.textEdit_hasta_mesaj.setGeometry(QtCore.QRect(130, 220, 311, 171))
        self.textEdit_hasta_mesaj.setObjectName("textEdit_hasta_mesaj")

        self.retranslateUi(hasta_ekrani)
        QtCore.QMetaObject.connectSlotsByName(hasta_ekrani)

    def retranslateUi(self, HastaEkrani):
        _translate = QtCore.QCoreApplication.translate
        HastaEkrani.setWindowTitle(_translate("HastaEkrani", "Hasta Ekranı"))
        self.label_hastabaslik.setText(_translate("HastaEkrani", "Randevulu Hasta Mesaj Ekranı"))
        self.label_2_hastabilgi.setText(_translate("HastaEkrani", "Duyuru : Şuan da doktordan bir bilgi bulunmamaktadır."))
        self.pushButton_hasta.setText(_translate("HastaEkrani", "Doktor Ekranına Mesaj Gönder"))

